config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  resources :products do
    get :who_bought, on: :member
  end

  root 'store#index', as: 'store_index'
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product)
    current_item = line_items.find_by(product_id: product.id)
    if current_item.present?
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product.id)
    end
    current_item.price = product.price
    current_item
  end

  def total_price
    line_items.map(&:total_price).sum
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :authorize
  before_action :set_current_cart, only: %i[show edit update destroy]

  def index
    @carts = Cart.all
  end

  def show
  end

  def new
    @cart = Cart.new
  end

  def edit
  end

  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to store_index_url }
      format.json { head :no_content }
      # TO DO
      # clean session without page reloading
      # format.js
    end
  end

  private

  def invalid_cart
    logger.error "Attempt to access invalid cart ##{params[:id]}"
    redirect_to store_index_url, notice: 'Invalid cart'
  end

  def set_current_cart
    if session[:cart_id] == params[:id].to_i
      @cart = Cart.find(params[:id])
    else
      invalid_cart
    end
  end

  def cart_params
    params.fetch(:cart, {})
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<article>
  <h2>Your Cart</h2>
  <table>
    <%= render(cart.line_items.sort) %>
    <tfoot>
      <tr>
        <th colspan="2">Total:</th>
        <th class="price"><%= number_to_currency(@cart.total_price) %></th>
      </tr>
    </tfoot>
  </table>
<!--   <%= button_to 'Empty cart', @cart, class: 'empty-cart-btn',
                                     method: :delete,
                                     remote: true,
                                     data: { confirm: 'Are you sure?' } %> -->

  <%= button_to 'Checkout', new_order_path, class: "checkout-btn",
                                            method: :get %>
</article>

app/views/carts/_form.html.erb
<%= form_with(model: cart) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>
<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<%= render @cart %>